version: "3.9"
services:
  db:
    image: postgres:13
    restart: always
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
  web:
    build: .
    volumes:
      - .:/map
    env_file:
      - .env.dev
    ports:
      - "3000:3000"
    depends_on:
      - db
