require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe '/gameworlds', type: :request do
  # This should return the minimal set of attributes required to create a valid
  # Gameworld. As you add validations to Gameworld, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) do
    { 'player_amount' => 100, 'round_amount' => 1000 }
  end

  let(:invalid_attributes) do
    { 'player_amount' => -100, 'round_amount' => -1000 }
  end

  # This should return the minimal set of values that should be in the headers
  # in order to pass any filters (e.g. authentication) defined in
  # GameworldsController, or in your router and rack
  # middleware. Be sure to keep this updated too.
  let(:valid_headers) do
    {}
  end

  describe 'GET /index' do
    it 'renders a successful response' do
      Gameworld.create!
      get gameworlds_url, headers: valid_headers, as: :json
      expect(response).to be_successful
    end
  end

  describe 'GET /show' do
    it 'renders a successful response' do
      gameworld = Gameworld.create!
      get gameworld_url(gameworld), as: :json
      expect(response).to be_successful
    end
  end

  describe 'POST /create' do
    context 'with valid parameters' do
      it 'creates a new Gameworld' do
        expect do
          post gameworlds_url,
               params: { gameworld: valid_attributes }, headers: valid_headers, as: :json
        end.to change(Gameworld, :count).by(1)
      end

      it 'renders a JSON response with the new gameworld' do
        post gameworlds_url,
             params: { gameworld: valid_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:created)
        expect(response.content_type).to match(a_string_including('application/json'))
      end
    end

    context 'with invalid parameters' do
      it 'does not create a new Gameworld' do
        expect do
          post gameworlds_url,
               params: { gameworld: invalid_attributes }, as: :json
        end.to change(Gameworld, :count).by(0)
      end

      it 'renders a JSON response with errors for the new gameworld' do
        post gameworlds_url,
             params: { gameworld: invalid_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:unprocessable_entity)
        expect(response.content_type).to eq('application/json; charset=utf-8')
      end
    end
  end
end
