require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe '/planets', type: :request do
  # This should return the minimal set of attributes required to create a valid
  # Planet. As you add validations to Planet, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) do
    gameworld = create(:gameworld)
    { 'movement_difficulty' => 0, 'recharge_multiplicator' => 0, 'planet_type' => 'default', 'x' => 0, 'y' => 0,
      'gameworld_id' => gameworld.id }
  end

  let(:invalid_attributes) do
    { 'movement_difficulty' => 0, 'recharge_multiplicator' => 0, 'planet_type' => 'default', 'x' => 0, 'y' => 0,
      'gameworld_id' => nil }
  end

  # This should return the minimal set of values that should be in the headers
  # in order to pass any filters (e.g. authentication) defined in
  # PlanetsController, or in your router and rack
  # middleware. Be sure to keep this updated too.
  let(:valid_headers) do
    {}
  end

  describe 'GET /index' do
    it 'renders a successful response' do
      Planet.create! valid_attributes
      get planets_url, headers: valid_headers, as: :json
      expect(response).to be_successful
    end
  end

  describe 'GET /show' do
    it 'renders a successful response' do
      planet = Planet.create! valid_attributes
      get planet_url(planet), as: :json
      expect(response).to be_successful
    end
  end
end
