---
openapi: 3.0.1
info:
  title: Map Service API
  description: This is the REST documentation for the Map Service
  version: v1.4
components:
  schemas:
    errors_object:
      type: object
      properties:
        status:
          type: integer
          example: 404
        error:
          type: string
          example: Not Found
        exception:
          type: string
          example: Couldn't find Gameworld with 'id'=1
    gameworld:
      type: object
      properties:
        id:
          type: string
          format: uuid
        spacestation_ids:
          type: array
          items:
            type: string
            format: uuid
        status:
          type: string
          enum:
          - inactive
          - active
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
    exploration:
      type: object
      properties:
        id:
          type: string
          format: uuid
        transcation_id:
          type: string
          format: uuid
        planet_id:
          type: string
          format: uuid
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
    planet:
      type: object
      properties:
        id:
          type: string
          format: uuid
        movement_difficulty:
          type: integer
        recharge_multiplicator:
          type: integer
        taken_at:
          type: string
          format: date-time
          nullable: true
        gameworld_id:
          type: string
          format: uuid
        planet_type:
          type: string
          enum:
          - default
          - spawn
          - spacestation
        neighbours:
          type: array
          items:
            type: object
            properties:
              planet_id:
                type: string
                format: uuid
              movement_difficulty:
                type: integer
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
        resource:
          oneOf:
          - "$ref": "#/components/schemas/resource"
          - type:
    resource:
      type: object
      properties:
        id:
          type: string
          format: uuid
        planet_id:
          type: string
          format: uuid
        max_amount:
          type: integer
        current_amount:
          type: integer
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
        resource_type:
          type: string
          enum:
          - coal
          - iron
          - gem
          - gold
          - platin
    mining:
      type: object
      properties:
        id:
          type: string
          format: uuid
        amount_requested:
          type: integer
        amount_mined:
          type: integer
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
paths:
  "/planets/{planet_id}/explorations":
    post:
      summary: Creates an exploration
      tags:
      - explorations
      parameters:
      - name: planet_id
        in: path
        schema:
          type: string
          format: uuid
        required: true
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/exploration"
        '422':
          description: Unprocessable Entity
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/exploration"
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/errors_object"
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                exploration:
                  type: object
                  properties:
                    transaction_id:
                      type: string
                      format: uuid
                  required:
                  - transaction_id
              required:
              - exploration
  "/gameworlds":
    get:
      summary: Retrieves all gameworlds
      tags:
      - gameworlds
      responses:
        '200':
          description: Return all available gameworlds
          content:
            application/json:
              schema:
                type: array
                items:
                  "$ref": "#/components/schemas/gameworld"
    post:
      summary: Creates a gameworld
      description: |-
        Creates a new Gameworld, for the given amount of players and sets it to
              "active" while setting all other gameworlds to "inactive". Publishes the `gameworld-created` Event.
      tags:
      - gameworlds
      parameters: []
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/gameworld"
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/errors_object"
        '422':
          description: Unprocessable Entity
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/errors_object"
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                gameworld:
                  type: object
                  properties:
                    player_amount:
                      type: integer
                      minimum: 1
                  required:
                  - player_amount
              required:
              - gameworld
  "/gameworlds/{gameworld_id}":
    get:
      summary: Retrieves a gameworld
      tags:
      - gameworlds
      parameters:
      - name: gameworld_id
        in: path
        schema:
          type: string
          format: uuid
        required: true
      responses:
        '200':
          description: Gameworld found
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/gameworld"
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/errors_object"
  "/planets/{planet_id}/minings":
    get:
      summary: Retrieves all minings
      tags:
      - minings
      parameters:
      - name: planet_id
        in: path
        schema:
          type: string
          format: uuid
        required: true
      responses:
        '200':
          description: Return all available minings
          content:
            application/json:
              schema:
                type: array
                items:
                  "$ref": "#/components/schemas/mining"
    post:
      summary: Creates a mining
      tags:
      - minings
      parameters:
      - name: planet_id
        in: path
        schema:
          type: string
          format: uuid
        required: true
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/mining"
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/errors_object"
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                mining:
                  type: object
                  properties:
                    amount_requested:
                      type: integer
                      minimum: 1
                  required:
                  - amount_requested
              required:
              - mining
  "/planets/{planet_id}/neighbours":
    get:
      summary: Retrieves all neighbours
      tags:
      - neighbours
      parameters:
      - name: planet_id
        in: path
        schema:
          type: string
          format: uuid
        required: true
      responses:
        '200':
          description: Return all available neighbours
          content:
            application/json:
              schema:
                type: array
                items:
                  "$ref": "#/components/schemas/planet"
  "/planets/{planet_id}/neighbours/{neighbour_id}":
    get:
      summary: Retrieves a planets neighbour
      tags:
      - neighbours
      parameters:
      - name: planet_id
        in: path
        schema:
          type: string
          format: uuid
        required: true
      - name: neighbour_id
        in: path
        schema:
          type: string
          format: uuid
        required: true
      responses:
        '200':
          description: Neighbour found
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/planet"
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/errors_object"
  "/planets":
    get:
      summary: Retrieves all planets
      parameters:
      - name: planet_type
        in: query
        schema:
          type: string
        description: Optional, planet type
      - name: taken
        in: query
        schema:
          type: boolean
        description: Optional, if the planet/spawn is already taken
      - name: page
        in: query
        schema:
          type: integer
        description: Optional, page. The API shows 50 planets per page
      tags:
      - planets
      responses:
        '200':
          description: Return all available planets for the active gameworld
          content:
            application/json:
              schema:
                type: array
                items:
                  "$ref": "#/components/schemas/planet"
  "/planets/{planet_id}":
    get:
      summary: Retrieves a planet
      tags:
      - planets
      parameters:
      - name: planet_id
        in: path
        schema:
          type: string
          format: uuid
        required: true
      responses:
        '200':
          description: Planet found
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/planet"
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/errors_object"
    patch:
      summary: Set the taken_at field of a planet/spawn
      tags:
      - planets
      description: Set the taken_at field of the planet to the given timestamp or
        null
      parameters:
      - name: planet_id
        in: path
        schema:
          type: string
          format: uuid
        required: true
      responses:
        '200':
          description: Taken at updated
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/planet"
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                planet:
                  type: object
                  properties:
                    taken_at:
                      type: string
                      format: date-time
                  required:
                  - taken_at
              required:
              - planet
  "/planets/{planet_id}/resources":
    get:
      summary: Retrieves all resources
      tags:
      - resources
      parameters:
      - name: planet_id
        in: path
        schema:
          type: string
          format: uuid
        required: true
      responses:
        '200':
          description: Return all available resources
          content:
            application/json:
              schema:
                type: array
                items:
                  "$ref": "#/components/schemas/resource"
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: localhost:3000
